### ISSUE TITLE
cargo build stuck on "esp-idf-sys(build)"

### ISSUE THREAD

**Issue by WerdoxDev** [esp-rs/esp-idf-sys#107]
when building with **cargo build** right when it reaches **esp-idf-sys(build)** cpu usage droppes to 0 and nothing happens
![image](https://user-images.githubusercontent.com/32638453/175364705-1a16c320-0eb2-4d02-bf38-e94d6f777f27.png)

**Comment by N3xed** [comment]
It's probably downloading the esp-idf, run with `-vv` to get more logs from the build script.

**Comment by WerdoxDev** [comment]
ohhhhh tnx :D

**Comment by N3xed** [comment]
No problem.
This is actually a cargo limitation right now, there is no way to report a long running task from a build script other than in very verbose mode (`-vv`).

Feel free to reopen if there's something else.

**Comment by WerdoxDev** [comment]
Well running with -vv does show that it's downloading, but then there are like 14 **CMake Warnings** followed by a **CMake Error** that fails the build
![image](https://user-images.githubusercontent.com/32638453/175381522-ac672a26-62e6-47ca-9170-4da0a9d8198b.png)

**Comment by N3xed** [comment]
Well (obviously) this shouldn't happen. You could try `cargo clean` and delete the `.embuild` directory to try again (maybe the git clone was interrupted).

Otherwise, please post the whole cargo output so we can try to debug this.

**Comment by WerdoxDev** [comment]
So i generated a clean project with the `esp-idf-template` and the build process went a lot further but still failed with this.
![image](https://user-images.githubusercontent.com/32638453/175467044-f5976f13-4c75-457d-9db3-12e19d41d8eb.png)

**Comment by WerdoxDev** [comment]
oh well nvm it seemed i did not install the toolchains correctly. just a simple reinstall and mnaually adding `LIBCLANG_PATH` to point to `libclang.dll` from `.espressif` worked!
