### ISSUE TITLE
Decide tools installation directory

### ISSUE THREAD

**Issue by N3xed** [esp-rs/esp-idf-sys#11]
- `pio` uses the platformio default in `~/.platformio`
- Should both strategies use the same directory (e.g. `<?>/.embuild/platformio` for `pio` and `<?>/.embuild/espressif` for `native`)?
- Where should the default directory be: home, workspace or out directory?

@ivmarkov already enumerated options with pros and cons:
> That is to say, whatever we decide to be the default, it should be for *both* build systems. To summarize, perhaps 4 options:
> - Option 1 - install and use the default global locations (i.e. `~/.platformio` and `~/.espressif`)
>   - Pros: 
>     - Does not pollute the binary crate with stuff that should be `.gitignore`-d
>     - Downloaded toolchains etc. can be re-used across builds of different binary crates
>     - Already downloaded toolchains etc. will just be used
>   - Cons:
>     - Patching ESP-IDF by the build itself is not so ideal as this is kinda build-specific
>     - Messes up with the global user configuration of either PlatformIO or Espressif `idf.py`
> - Option 2 - install and use an `embuild`-specific global location (i.e. `~/.embuild/platformio` and `~/.embuild/espressif`)
>   - Pros: 
>     - Does not pollute the binary crate with stuff that should be `.gitignore`-d
>     - Downloaded toolchains etc. can be re-used across builds of different binary crates
>     - Already downloaded toolchains etc. will just be used
>     - Does not mess up with the user configuration
>   - Cons:
>     - Patching ESP-IDF by the build itself is not so ideal as this is kinda build-specific
>     - Creates something outside the binary crate directory
> - Option 3 - install and use an `embuild`-specific location within the *root* of the binary crate (i.e. `.embuild/platformio` and `.embuild/espressif`)
>   - Pros: 
>     - Does not mess up with the user configuration
>     - No global state
>     - Patching ESP-IDF OK as it remains build specific 
>   - Cons:
>     - Pollutes the binary crate with stuff that should be `.gitignore`-d
>     - Still does not follow the cargo policy that everything should be in the $OUT_DIR
>     - Downloaded toolchains etc. cannot be re-used across builds of different binary crates
> - Option 4 - install and use an `embuild`-specific location within the `OUT_DIR` of the binary crate (i.e. `$OUT_DIR/embuild/platformio` and `$OUT_DIR/embuild/espressif`)
>   - Pros: 
>     - Does not mess up with the user configuration
>     - No global state
>     - Patching ESP-IDF OK as it remains build specific 
>     - Does not pollute the binary crate with stuff that should be `.gitignore`-d
>     - Does not follow the cargo policy that everything should be int he $OUT_DIR
>     - `cargo clean` means everything is removed, including ESP-IDf patches. Really clean state
>   - Cons:
>     - `cargo clean` means everything will be re-downloaded again
>     - Downloaded toolchains etc. cannot be re-used across builds of different binary crates
> 
> Preferences for a default?
> Mines are:
> * Option 2
> * Option 3 (if global state is something you guys feel uneasy) 
> 
> In any case, having a flag/switch/env var/whatever so that the build framework is operating in Option 1 mode is a prerequisite IMO.

**Comment by N3xed** [comment]
Okay so I think what we decided on was:

For the native build:
- Global install dir: `~/.espressif`
- Local install dir (used by default): `<workspace-dir>/.embuild/espressif`

For the pio build:
- Continue to use the global install dir `~/.platformio`, which is the pio default.

**Comment by N3xed** [comment]
Well, installing the tools into `~/.espressif` shouldn't cause issues, I see that (because this uses the exact same mechanism to install the tools as the esp-idf itself, as far as I know). But the problem was with installing the esp-idf source. Currently, both the source and tools are always installed in the same directory. And when installing the source in the global location and patching it, that could cause problems, should the user installation of the esp-idf source and our installation coincide.

With #19, this problem still exists, as again, both the source and tools are always installed in the same location. Changing this would make it more complicated. 
The default is to install both things locally, but the user can opt into the global install. Also, I think the goal is to eventually not have to patch the esp-idf. Additionally, unless a specific hash is installed, the esp-idf source folder always gets the tag or branch 
name suffixed so this should also prevent collisions in most cases.

So with that, I think that this shouldn't really be an issue. Please tell me if you think otherwise.

> For IDF itself, it is typically not installed into ~/.espressif

That's good to know.

**Comment by ivmarkov** [comment]
The PlatformIO aspect of this should now be fixed by https://github.com/esp-rs/esp-idf-sys/commit/9022587a6fdd9defb7f1e2eec8c4100705407b16

I'll publish a new release now, with these changes as well as the previous ones from @N3xed that unified the handling of `sdkconfig*` files and glob file copies.
