### ISSUE TITLE
Problem in adding extra component in my workspace

### ISSUE THREAD

**Issue by farbodpm** [esp-rs/esp-idf-sys#120]
I have tested the extra component in a single project and it works great. but when I am trying to work on a project that have several library that depends on esp-idf-sys. extra components binding doesn't work.

**Comment by N3xed** [comment]
Well, only saying that it doesn't work doesn't really help anyone.

What could be the issue? What is the error (if there is one) that you're getting? What could be a potential fix?

Are you aware of the [`ESP_IDF_SYS_ROOT_CRATE` and `CARGO_WORKSPACE_DIR`](https://github.com/esp-rs/esp-idf-sys#build-configuration) environment variables that exist for edge-cases of virtual workspaces and custom workspace setups?

**Comment by farbodpm** [comment]
Hi , 
Thanks for your response. I just found out about ESP_IDF_SYS_ROOT_CRATE and I will check it.

**Comment by N3xed** [comment]
I'll close this for now, feel free to reopen if this didn't work.
