### ISSUE TITLE
esp_idf_sys::esp_log_level_set did not work as expected

### ISSUE THREAD

**Issue by elotom** [esp-rs/esp-idf-sys#151]
It looks like the log level can't be changed during runtime with esp_log_level_set. I'm using ESP32-S3.
Code that I'm using in main to replicate the problem:

```rust
// Default log level is 3 - Info
    info!("Info level");
    error!("Error level");
    unsafe {
        let level = esp_idf_sys::esp_log_level_get("*".as_ptr() as *const i8);
        dbg!(level);
        esp_idf_sys::esp_log_level_set("*".as_ptr() as *const i8, 1);
        let level = esp_idf_sys::esp_log_level_get("*".as_ptr() as *const i8);
        dbg!(level);
    }
    info!("Info level");
    error!("Error level");
```

Terminal output:
![image](https://user-images.githubusercontent.com/111735149/200344367-cf4ba7a9-6c8e-44a8-a140-13644ffbfa36.png)

I was expecting that only the Error level will be printed after setting the log level to 1(Error).

**Comment by jendakol** [comment]
FYI I'm struggling the same way, trying to set logging to a `DEBUG`.

**Comment by ivmarkov** [comment]
Calling `esp_log_level_set` is necessary, but not sufficient. Check this part of the ESP IDF documentation: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/log.html
