### ISSUE TITLE
How can I use `esp_crc*` functions

### ISSUE THREAD

**Issue by rukai0712** [esp-rs/esp-idf-sys#169]
I cannot import `esp_crc*` functions.

It seems the `esp_crc.h` is not included in `bindings.h` file 
https://github.com/esp-rs/esp-idf-sys/blob/ec2e561a9690567d7e00ab796cac2f41383bbbf1/src/include/esp-idf/bindings.h#L7

Is there any reason to comment out this line?

**Comment by ivmarkov** [comment]
Do not remember anymore. If you need it, try to enable the include, and if/when it works, open a PR.
