### ISSUE TITLE
Add support for ESP32-C6

### ISSUE THREAD

**Issue by konradmoesch** [esp-rs/esp-idf-sys#172]
Using ESP-IDF 5.1 or the master, I would like to be able to compile for the ESP32-C6

Currently, using the template, I end up in a bootloop (`bad load address range`)

What is needed to get support for the C6? I am willing to contribute

**Comment by ivmarkov** [comment]
As a start, if you can paste here your complete boot loader log, so that we can understand what is going wrong.

**Comment by ivmarkov** [comment]
Closing, inactive.
