### ISSUE TITLE
Atomic linking undefined for esp32c6 and esp-idf release/5.1

### ISSUE THREAD

**Issue by Nassiel** [esp-rs/esp-idf-sys#200]
# ESP32c6 

## Description

After solving some MCU issues to allow the proper compilation of C6 instead of C3, (more info in PR #199), more info after this intro. The IDF compiles, but when linking, LD raises some errors for atomic functions not found.

IMO, I think is related to the `march=rv32imac_zicsr_zifencei` compilation chain, including atomic functions and the `imc` image that is being generated without those atomics.

I guess, that one option is to allow a new target that supports it, something like `riscv32imac-esp-espidf`.

## Full error

Here is the [full gist](https://gist.github.com/Nassiel/3beed5c3509d826448b5a5bf6acf8053) with the error.

And one example for fast review:
```
/home/<myhome>/Code/rust/hello-world-idf/.embuild/espressif/tools/riscv32-esp-elf/esp-12.2.0_20230208/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: /home/<myhome>/Code/rust/hello-world-idf/target/riscv32imc-esp-espidf/release/deps/libstd-7b0dc1c1a90dc68d.rlib(std-7b0dc1c1a90dc68d.std.7e9a7e7f1a18ad77-cgu.14.rcgu.o): in function `std::sys::unix::os::env_read_lock':
          std.7e9a7e7f1a18ad77-cgu.14:(.text._ZN3std3sys4unix2os13env_read_lock17hec72ca02d0ec1027E+0x14): undefined reference to `__atomic_load_4'
```

## Long story

I started trying to compile for C6 one week ago or so, first I found many issues, but when it was compiling successfully, I realized that the bootloader was expecting a C3 chip instead of the C6. 

Then, I tried a custom bootloader but it was wrong, so @vollbrecht guided me to find that the esp-idf-sys was doing an automatic interpretation and assuming that it was a C3 just because the target was risc.

Then, I forced the MCU, to discover that esp-idf-sys doesn't support `esp32c6` MCU. I downloaded the repo, modified it and pointed my cargo to my local repo. Then IDF compiles properly for C6 but the linking issue was raised.

The command line to compile the solution is:
`CRATE_CC_NO_DEFAULTS=1 RUST_BACKTRACE=full cargo espflash flash --monitor --release`

The project was created using the esp-rs-template and then added in the `.cargo/config.toml` the next config:
```
[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
rustflags = ["-C", "default-linker-libraries", "--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# Note: these variables are not used when using pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "release/v5.1"
MCU = "esp32c6"
```

If more info of the process or trials are required, happy to include it so please let me know.

**Comment by ivmarkov** [comment]
This should now be fixed, and if you `[patch.crates-io]` all of `embedded-svc`, `esp-idf-sys`, `esp-idf-hal` and `esp-idf-svc` with their `master` versions, you should be able to build for C6 without any linking errors.

The pin layout for the C6 might be a bit incorrect (for one, I can't find info which pins are RTC pins) and there might be other gaps in the HAL impl. In any case, I don't have a C6 yet, so it would be good if you can test it a bit.

Don't forget to check [this section](https://github.com/esp-rs/esp-idf-sys#esp32-c6-preliminary-support) in the readme w.r.t. using the custom `riscv32imac` target, which is not upstreamed to Rust yet.

Feel free to reopen in case of issues.
