### ISSUE TITLE
Use the new DAC driver

### ISSUE THREAD

**Issue by 823984418** [esp-rs/esp-idf-sys#209]
https://github.com/espressif/esp-idf/blob/release/v5.1/docs/en/migration-guides/release-5.x/5.1/peripherals.rst

Does this library already have an update plan?

**Comment by ivmarkov** [comment]
The update plan is mainly driven by contributors. If somebody needs a driver (or a newer version of an existing driver), then ideally the individual submits a PR.

So you could be the one contributing safe Rust bindings to the DAC driver!

With that said, I'm closing this as we already have https://github.com/esp-rs/esp-idf-hal/issues/28
