### ISSUE TITLE
Add bindings for SIMD operations

### ISSUE THREAD

**Issue by MangioneAndrea** [esp-rs/esp-idf-sys#215]
The environment supports some SIMD operations as described here: https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf

In Specific
> 1.6.4 Arithmetic Instructions
> Arithmetic instructions mainly use the SIMD (Single Instruction Multiple Data) principle for vector data operations,
> including vector addition, vector multiplication, vector complex multiplication, vector multiplication accumulation,
> vector and scalar multiplication accumulation, etc

It would be great to have those calls in the rust API as they might speed up a lot of operations

I'm a beginner with idf, so I'd like to hear the opinion of somebody more experienced before trying to implement this myself, maybe I missed something in the docs :)

Cheers!

**Comment by Vollbrecht** [comment]
There is nothing real preventing you from using custom inline assembly instruction within your rust code. So this is a bit out of scope for this crate. In the end you either let the compiler do it's thing such that it emits the correct instructions or you have to manually write them yourself. 

I can only maybe see that there is maybe a lag of guidance or documentation around that points, but other than that i don't see a direct actionable item here. 

With that in mind i am closing the issue.
