### ISSUE TITLE
OTA_SIZE_UNKNOWN is u32 while esp_ota_begin now wants usize

### ISSUE THREAD

**Issue by faern** [esp-rs/esp-idf-sys#217]
In `esp-idf-sys 0.32.0` the argument `image_size` of `esp_ota_begin` became a `usize` rather than a `u32`. But the constant `OTA_SIZE_UNKNOWN` is still a `u32`. This means that the place where the constant is supposed to be used, it's not compatible. I can of course just cast it, but it would be more ergonomic if they had the same types.

**Comment by ivmarkov** [comment]
`esp-idf-sys` is really just raw bindings. Specifically OTA_SIZE_UKNOWN is probably a `#define` and as such the Rust bindgen utility does not really know its type, and arbitrary defines these as either `i32` and `u32`. 

Under some special circumstances, we can force bindgen - for selected C macros - to derive a different type, but this is a manual effort for each such constant, and as such, we only do it for constants which are used very often. I don't think `OTA_SIZE_UNKNOWN` can be justified to fall into this category.
