### ISSUE TITLE
esp-idf-sys fails to build because of CMake version

### ISSUE THREAD

**Issue by MathyV** [esp-rs/esp-idf-sys#233]
On an older system (in this case Mint Una), where cmake < 3.20, the build will fail claiming that you need at least version 3.20 of cmake. Embuild installs a custom cmake in `~/.espressif/tools/cmake` but it doesn't seem to be used (in all cases?).

A workaround is adding `export PATH="${HOME}/.espressif/tools/cmake/3.24.0/bin/:${PATH}"` to `export-esp.sh`, after which the build does go through.

The version installed in the system is 3.16 btw. Mint Una and Ubuntu Focal on which it is based are LTS until April 2025.

**Comment by Vollbrecht** [comment]
With the updated [embuild](https://github.com/esp-rs/embuild/pull/85) crate we now make sure in the installation step of the tools, that a proper version is installed, and we also export them automatically in such a way that this version is used over the version potentially provided by the system.
