### ISSUE TITLE
Windows path length message is wrong.

### ISSUE THREAD

**Issue by Timmmm** [esp-rs/esp-idf-sys#293]
I get this error:

```
  Error: Too long output directory: `\\?\D:\lockfw\target\riscv32imac-esp-espidf\release\build\esp-idf-sys-eac617bcbe734de9\out`. Shorten your project path down to no more than 10 characters (or use WSL2 and its native Linux filesystem). Note that tricks like Windows `subst` do NOT work!       
```

However as you can see my project path is `D:\lockfw` which is only 9 characters. But if you search for that error, it's from [here](https://github.com/esp-rs/esp-idf-sys/blob/master/build/common.rs#L441):

```
    #[cfg(windows)]
    {
        if out_dir.len() > 88 {
            report(format!("Too long output directory: `{out_dir}`. Shorten your project path down to no more than 10 characters (or use WSL2 and its native Linux filesystem). Note that tricks like Windows `subst` do NOT work!"))?;
        }
    }
```

That's checking the length of `\\?\D:\lockfw\target\riscv32imac-esp-espidf\release\build\esp-idf-sys-eac617bcbe734de9\out` which is 90 characters. So my path has to actually be a maximum of 8 characters!? Three of which are `D:\` so I get 5 characters??

That's practically unusable. I think at that point there has to be a better solution. What part of the compilation process needs these really long paths?

I did also try `ESP_IDF_PATH_ISSUES=warn` and it compiled successfully (as far as I can tell). So maybe the check is just wrong?

**Comment by ivmarkov** [comment]
No the check is not wrong (we cant control the fact that Rust normalizes the path even further) and yes, your project path needs to be very short.

Please look at existing closed PRs and bugs. This topic has been discussed at length, including the dangers of setting this parameter to `warn`.

A real fix (normal path length) is very, very involved as discussed multiple times.es elsewhere.
