### ISSUE TITLE
I was trying to do a no-std version of Led using esp32c3 board and the build keeps failing, how can I solve this?

### ISSUE THREAD

**Issue by jonyach** [esp-rs/esp-idf-sys#310]
error: failed to run custom build command for `xtensa-lx-rt v0.16.0`

Caused by:
  process didn't exit successfully: `/home/jonyach/esp32c3/led1-nstd/target/release/build/xtensa-lx-rt-c129fc02a15c3962/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/jonyach/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xtensa-lx-rt-0.16.0/build.rs:25:14:
  Either the esp32, esp32s2, esp32s3 or esp8266 feature must be enabled
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by Vollbrecht** [comment]
Are you trying to mix the esp-hal with esp-idf-sys?  They are not compatible, e.g you either have to use esp-hal or esp-idf-hal/svc ontop of esp-idf-sys
