### ISSUE TITLE
rmt_rx.h conflicts with mcpwm_prelude.h on dobule definiton of extra_flags

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/esp-idf-sys#311]
[This](https://github.com/espressif/esp-idf/blob/0453e8608bde98133a427a74ae61d272770b1bfd/components/esp_driver_rmt/include/driver/rmt_rx.h#L59) is also defined in [here](https://github.com/espressif/esp-idf/blob/0453e8608bde98133a427a74ae61d272770b1bfd/components/esp_driver_mcpwm/include/driver/mcpwm_cap.h#L141)  and clang topples over this.

**Comment by ivmarkov** [comment]
Fix by https://github.com/esp-rs/esp-idf-sys/commit/6e20a81c128ace4e4c892478ecff19edf09d8c49
