### ISSUE TITLE
Failed to run Python dependency check

### ISSUE THREAD

**Issue by doofin** [esp-rs/esp-idf-sys#344]
Hi, I got below err when compile rust projects: 

```
failed to run custom build command for `esp-idf-sys v0.33.7`
....
Failed to run Python dependency check.  Python:
    Error: 255
```

**Comment by ivmarkov** [comment]
Nice. You need to paste the full log output here. "255" is impossible to debug.

Also, double-check if you have installed all pre-requisites, by following the README in the `esp-idf-template` repo.

**Comment by doofin** [comment]
I updated the esp idf version and seems ok now, thanks!
