### ISSUE TITLE
How to set flash size

### ISSUE THREAD

**Issue by Verequies** [esp-rs/esp-idf-sys#37]
I'm currently trying to change the flash size from 2 MB to 8 MB as I am getting the following warning:
```
W (269) spi_flash: Detected size(8192k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
```
However I am unsure how to do this properly. Changing the flash size in the `sdkconfig` does not work either.

**Comment by MabezDev** [comment]
Flash size in the binary image header is managed by esptool.py or espflash, not by esp-idf-sys.
