### ISSUE TITLE
 Use tags to mark crate release versions

### ISSUE THREAD

**Issue by kevin-june** [esp-rs/esp-idf-sys#53]
Is it possible/reasonable to tag versions of the `esp-idf-sys` crate that are released to crates.io? I'm hoping to see at a glance what the source is for different crate versions. Tags seem like a natural approach for this.

**Comment by N3xed** [comment]
Yup, good point.
We should add automatic tag creation on our `Publish` workflow.
Until then I'll manually create tags.
