### ISSUE TITLE
404 not found for the doc URL

### ISSUE THREAD

**Issue by tatsuya6502** [esp-rs/esp-idf-sys#59]
When open the doc URL from a web browser:

- https://esp-rs.github.io/esp-idf-sys/

it will be redirected to this URL:

- https://esp-rs.github.io/esp-idf-sys/build_wheel

However, the URL does not exist so GitHub Pages will return 404 file not found error.

It seems the correct URL will be:

- https://esp-rs.github.io/esp-idf-sys/esp_idf_sys/

Thanks!

**Comment by MabezDev** [comment]
This was a mistake on my end, which I fixed in https://github.com/esp-rs/esp-idf-sys/pull/55.

The docs redirect will work when we publish our next release. I'll keep this open until then.

**Comment by ivmarkov** [comment]
Fixed with the newest published release.
