### ISSUE TITLE
Error compiling - PlatformIO

### ISSUE THREAD

**Issue by DavidCarl** [esp-rs/esp-idf-sys#73]
Hello

I am attempting to make my own ESP32 Rust project, however when I try to compile it using `cargo build` I get the following error:

```
Caused by:
  process didn't exit successfully: `/home/carl/Documents/git/github/davidcarl/ESP32-Build/target/debug/build/esp-idf-sys-b9e81c780502d3bf/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ESP_IDF_TOOLS_INSTALL_DIR
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG_DEFAULTS
  cargo:rerun-if-env-changed=MCU
  Found compatible PlatformIO Core 5.2.5 -> /home/carl/Documents/git/github/davidcarl/ESP32-Build/.embuild/platformio/penv/bin/platformio
```

I am able to build the rust-esp32-std-demo project, and I have attempted to gut this project for all the necessary dependencies, however I run into this error now.

I have attempted to reinstall my toolchain (multipletimes), `cargo clean` and `cargo update` however it still just keep not working.

Thanks in advanced

**Comment by MabezDev** [comment]
Without seeing the project, it's pretty hard to tell. I would try stripping back `rust-esp32-std-demo` one thing at a time until you run into compilation errors.

**Comment by ivmarkov** [comment]
Also - is this the complete compiler output?
I think we are missing the stderr output?

**Comment by DavidCarl** [comment]
hey Sorry

I found the issue, it was simply to me being an idiot and forgot to persist the environment variables for the ESP build chain, sorry about that :)
