### ISSUE TITLE
Undeclared defines while building native (DR_REG_EMAC_BASE)

### ISSUE THREAD

**Issue by teamplayer3** [esp-rs/esp-idf-sys#77]
I try to build the crate for the esp32c3 with native feature #10 enabled and get the following error:

```
FAILED: esp-idf/esp_eth/CMakeFiles/__idf_esp_eth.dir/src/esp_eth_mac_openeth.c.obj
In file included from /root/.espressif/esp-idf-release/v4.4/components/esp_eth/src/esp_eth_mac_openeth.c:36:
  /root/.espressif/esp-idf-release/v4.4/components/esp_eth/src/openeth.h: In function 'openeth_tx_desc':
  /root/.espressif/esp-idf-release/v4.4/components/esp_eth/src/openeth.h:40:37: error: 'DR_REG_EMAC_BASE' undeclared (first use in this function); did you mean 'DR_REG_HMAC_BASE'?
   #define OPENETH_BASE                DR_REG_EMAC_BASE
...
```

I use the version `release/v4.4` and have `CONFIG_ETH_USE_OPENETH=y` enabled.

It could be a wrong configuration, so I tried to use the [cargo-idf tool](https://github.com/N3xed/embuild?branch=cargo-idf#afb5cb1a). But it depends on the same build, so it fails with the same error.

I recognized the macro is defined in soc/esp32/../reg_base.h. But this header is not be included when building for the esp32c3 in my configuration.

**Comment by ivmarkov** [comment]
`CONFIG_ETH_USE_OPENETH=y` only works for the Xtensa `esp32` chip & target.
