### ISSUE TITLE
LoadProhibited exception when using `EspMutex`

### ISSUE THREAD

**Issue by N3xed** [esp-rs/esp-idf-sys#8]
The implementation for `EspMutex` was recently changed from using a `pthread_mutex_t` to a `*mut pthread_mutex_t`. This is incorrect as when locking, the [`pthread_mutex_lock`](https://github.com/espressif/esp-idf/blob/1ca2afd982230e4cbf021c58137f3141c1870572/components/pthread/pthread.c#L654) function calls [`pthread_mutex_init_if_static`](https://github.com/espressif/esp-idf/blob/1ca2afd982230e4cbf021c58137f3141c1870572/components/pthread/pthread.c#L641) which dereferences the mutex pointer. Because this pointer is initially set to `PTHREAD_MUTEX_INITIALIZER` (`0xFFFFFFFF`), this causes a load to this address which is invalid and causes a `LoadProhibited` exception.

**Comment by ivmarkov** [comment]
Sorry for this stupid mistake. Hopefully fixed now.

**Comment by N3xed** [comment]
Yup, fixed it.
