### ISSUE TITLE
vPortEvaluateYieldFromISR isn't exported?

### ISSUE THREAD

**Issue by Jezza** [esp-rs/esp-idf-sys#85]
`esp-idf-hal` uses `vPortEvaluateYieldFromISR` within `interrupt.rs`, but doesn't seem to be exported from this project.

**Comment by ivmarkov** [comment]
`esp-idf-hal` is using `vPortEvaluateYieldFromISR` [conditionally](https://github.com/esp-rs/esp-idf-hal/blob/master/src/interrupt.rs#L87), as it is not available on all ESP chips. I strongly suggest you use [this function](https://github.com/esp-rs/esp-idf-hal/blob/master/src/interrupt.rs#L76) if possible and not going down straight to `FreeRTOS`, as that would mean calling different things for different ESP chips (there is a compat layer amongst all of them but it is in the form of macros / C static functions so it is not visible from Rust).
